### ISSUE TITLE
APIs needed for 1.0

### ISSUE THREAD

**Issue by chancancode** [tildeio/libcruby-sys#1]
### Legend

Please hold off on adding these items for now:

* 🤔 I have some doubts (that this is a necessary/good idea/...)
* ❗️ This is a custom extension to the Ruby C API (through runtime C code in the ext)

* * *

* https://github.com/tildeio/helix/blob/master/src/class_definition.rs
  * [x] `VALUE`
  * [x] `rb_define_class` #8
  * [ ] `rb_define_alloc_func` #46
  * [x] `rb_intern`
  * [x] `rb_const_get`
  * [x] `rb_cObject`
  * [x] `rb_define_method`
  * [x] `rb_define_singleton_method` #9
  * [x] `rb_undef_method` #10
* https://github.com/tildeio/helix/blob/master/src/errors.rs
  * [x] `VALUE`
  * [ ] `SPRINTF_TO_S` 🤔 #47
  * [x] `rb_eRuntimeError`
* https://github.com/tildeio/helix/blob/master/src/lib.rs
  * [x] `ID`
  * [x] `rb_eTypeError`
  * [x] `rb_intern_str` #21
  * [x] `rb_define_method`
  * [x] `rb_cObject`
  * [x] `rb_define_class` #8
  * [x] `rb_inspect` #12
* https://github.com/tildeio/helix/blob/master/src/macros/alloc.rs
  * [x] `VALUE`
  * [ ] `Data_Wrap_Struct` #46
* https://github.com/tildeio/helix/blob/master/src/macros/coercions.rs
  * [x] `VALUE`
  * [x] `rb_obj_class` #13
  * [x] `rb_obj_classname` #14
  * [ ] `Data_Get_Struct_Value` ❗️ #46
  * [ ] `Data_Set_Struct_Value` ❗️ #46
  * [x] `Qnil`
* https://github.com/tildeio/helix/blob/master/src/macros/init.rs
  * [x] `VALUE`
  * [x] `Qnil`
  * [ ] `Data_Set_Struct_Value` ❗️ #46
* https://github.com/tildeio/helix/blob/master/src/coercions/bool.rs
  * [x] `VALUE`
  * [x] `Qtrue`
  * [x] `Qfalse`
  * [ ] `RB_TYPE_P` 🤔 #49
  * [ ] `T_TRUE` 🤔 #49
  * [ ] `T_FALSE` 🤔 #49
* https://github.com/tildeio/helix/blob/master/src/coercions/float.rs
  * [x] `VALUE`
  * [ ] `RB_TYPE_P` 🤔#49
  * [ ] `T_FLOAT` 🤔#49
  * [ ] `T_FIXNUM` 🤔 #49
  * [ ] `T_BIGNUM` 🤔 #49
  * [ ] `NUM2F64` 🤔 #51
  * [ ] `F642NUM` 🤔 #51
* https://github.com/tildeio/helix/blob/master/src/coercions/hash.rs
  * [x] `VALUE`
  * [ ] `RB_TYPE_P` 🤔 #49
  * [ ] `T_HASH` 🤔 #49
  * [ ] `RHASH_SIZE` #50
  * [x] `rb_hash_foreach` #19
  * [x] `rb_hash_new` #19
  * [x] `rb_hash_aset` #19
  * [x] `st_retval` 🤔
* https://github.com/tildeio/helix/blob/master/src/coercions/integers.rs
  * [x] `VALUE`
  * [ ] `RB_TYPE_P` 🤔 #49
  * [ ] `T_FIXNUM` 🤔 #49
  * [ ] `T_BIGNUM` 🤔 #49
  * [ ] `NUM2USIZE` 🤔 ❗️  #51
  * [ ] `USIZE2NUM` 🤔 ❗️  #51
  * [ ] `NUM2ISIZE` 🤔 ❗️  #51
  * [ ] `ISIZE2NUM` 🤔 ❗️ #51
  * [ ] `NUM2U64` 🤔 ❗️  #51
  * [ ] `U642NUM` 🤔 ❗️  #51
  * [ ] `NUM2I64` 🤔 ❗️  #51
  * [ ] `I642NUM` 🤔 ❗️  #51
  * [ ] `NUM2U32` 🤔 ❗️  #51
  * [ ] `U322NUM` 🤔 ❗️  #51
  * [ ] `NUM2I32` 🤔 ❗️  #51
  * [ ] `I322NUM` 🤔 ❗️  #51
* https://github.com/tildeio/helix/blob/master/src/coercions/mod.rs
  * [x] `VALUE`
* https://github.com/tildeio/helix/blob/master/src/coercions/option.rs
  * [x] `VALUE`
  * [x] `Qnil`
* https://github.com/tildeio/helix/blob/master/src/coercions/slice.rs
  * [x] `rb_ary_new_capa`
  * [x] `rb_ary_push`
* https://github.com/tildeio/helix/blob/master/src/coercions/string.rs
  * [x] `VALUE`
  * [ ] `RB_TYPE_P` 🤔 #49
  * [ ] `T_STRING` 🤔 #49
  * [x] `rb_enc_get_index` #20
  * [x] `rb_utf8_encindex` #20
  * [ ] `rb_str_valid_encoding_p` ❗️ 
  * [ ] `rb_str_ascii_only_p` ❗️ 
  * [x] `RSTRING_LEN` #35
  * [x] `RSTRING_PTR` #35
* https://github.com/tildeio/helix/blob/master/src/coercions/symbol.rs
  * [x] `VALUE`
  * [ ] `RB_TYPE_P` 🤔 #49
  * [ ] `T_SYMBOL` 🤔 #49
  * [x] `rb_sym2id`
  * [x] `rb_id2sym`
* https://github.com/tildeio/helix/blob/master/src/coercions/tuples.rs
  * [x] `VALUE`
  * [ ] `RB_TYPE_P` 🤔 #49
  * [ ] `T_ARRAY` 🤔 #49
  * [x] `RARRAY_LEN` #45
  * [x] `rb_ary_entry` #18
  * [x] `rb_ary_new_capa`
  * [x] `rb_ary_push`
* https://github.com/tildeio/helix/blob/master/src/coercions/unit.rs
  * [x] `VALUE`
  * [x] `Qnil`
* https://github.com/tildeio/helix/blob/master/src/coercions/value.rs
  * [x] `VALUE`
* https://github.com/tildeio/helix/blob/master/src/coercions/vec.rs
  * [x] `VALUE`
  * [ ] `RB_TYPE_P` 🤔 #49
  * [ ] `T_ARRAY` 🤔 #49
  * [x] `RARRAY_LEN` #45
  * [x] `rb_ary_entry` #18
  * [x] `rb_ary_new_capa`
  * [x] `rb_ary_push`
